server:
  port: 8021
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: UserCoreService
          uri: lb://UserCoreService
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: HystrixFallbackHandler
                fallbackUri: forward:/defaultfallback
        - id: BrandService
          uri: lb://ItemsCoreService/brand
          predicates:
            - Path=/api/brand/**
          filters:
            - StripPrefix=1
        - id: ItemsCoreService2
          uri: lb://ItemsCoreService
          predicates:
            - Path=/item/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: HystrixFallbackHandler
                fallbackUri: forward:/defaultfallback
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
        - id: mall-demo
          uri: lb://mall-demo
          predicates:
            - Path=/mall-demo/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8021/user/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: true

org:
  my:
    jwt:
      #跳过认证的路由
      adminurls:
        - /baidu
