server:
  port: 8021
spring:
  boot:
    admin:
      client:
        url: http://localhost:8090
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id

  security:
    oauth2:
      resourceserver:
        #jwt:
          #jws-algorithm: www12345
        #resourceserver:
        jwt:
          public-key-location: classpath:q7w.txt


        #jwk-set-uri: 'http://localhost:8021/user/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
secure:
  ignore:
    urls:
      - /login/*